'use client';

//! This is the code for the CPU Breakdown page


import React from "react";
import { motion } from "framer-motion";

import Navbar from "../components/navbar";

const CpuBreakdown: React.FC = () => {
    return (
        <>
            <head>
                <title>CPU Information</title>
            </head>

            <Navbar />

            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="max-w-2xl mx-auto p-4"
            >
                <div className="">
                    <h1 className="text-3xl font-bold mb-4">CPU Information</h1>
                    
                    <p className="mb-4">
                        The CPU, or central processing unit, is the primary component of a computer responsible for executing instructions and performing calculations. It is often referred to as the &quot;brain&quot; of the computer and plays a crucial role in overall system performance.
                    </p>

                    <ul className="list-disc pl-6 mb-4">
                        <li>Cores: The number of cores in a CPU represents the number of independent processing units. Each core can handle separate tasks simultaneously, improving overall performance and multitasking capabilities.</li>
                        <br></br>
                        <li>Threads: Threads refer to the number of simultaneous execution paths within a CPU core. Each thread can handle a separate set of instructions, allowing for parallel processing and improved performance in multithreaded applications.</li>
                        <br></br>
                        <li>Frequency: CPU frequency, measured in GHz (gigahertz), represents the speed at which the CPU can execute instructions. A higher frequency generally indicates faster processing capabilities.</li>
                        <br></br>
                        <li>Cache: CPU cache is a small, high-speed memory that stores frequently accessed data. It helps reduce the time it takes to access data from the main memory, improving overall performance.</li>
                        <br></br>
                        <li>TDP (Thermal Design Power): TDP represents the maximum amount of heat generated by a CPU under normal operating conditions. It is an important factor to consider for system cooling and power supply.</li>
                    </ul>
                </div>
            </motion.div>
        </>
    );
};

export default CpuBreakdown;
